name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Pipenv
      run: python3 -m pip install pipenv

    - name: Pipenv install
      run: pipenv install

    - name: Run uni tests
      run: pipenv run python -m unittest tests/*.py